### ISSUE TITLE
如何在远程服务器上进行部署

### ISSUE THREAD

**Issue by Xavier-Zeng** [jicg/liteblog#6]
请问大佬是如何部署此应用到远程服务器的呢？

**Comment by jicg** [comment]
linux 使用docker ，wins 用安装包 https://github.com/jicg/liteblog/files/2481053/liteblog.msi.zip

**Comment by Xavier-Zeng** [comment]
> linux 使用docker ，wins 用安装包 https://github.com/jicg/liteblog/files/2481053/liteblog.msi.zip

大佬有没有用nginx进行部署呢？我用nginx进行部署的时候，将nginx.config中的server配置如下：
```bash
server {
    listen       80;
    server_name  localhost;

    charset utf-8;
    access_log  /home/a.com.access.log;

    location /(css|js|fonts|img)/ {
        access_log off;
        expires 1d;

        root /home/go/src/beeblog/static;
        try_files $uri @backend;
    }

    location / {
        try_files /_not_exists_ @backend;
    }

    location @backend {
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host            $http_host;

        proxy_pass http://127.0.0.1:8080;
    }
}
```
用其他主机的客户端浏览器进行登陆的时候，浏览器显示长时间无法响应。我以前没有在远程服务器部署过，请问大佬知道怎么解决吗？

**Comment by jicg** [comment]
你代理的端口是80还是8080？


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by jicg** [comment]
server_name  一般 都是写域名的好像。
